/**
 * Hybrid Leads: Google Sheet bridge.
 * Generated by the it-leads tool for one account. It creates the sheet on first contact, then adds new rows
 * when the tool posts to it. It never deletes rows or columns, never touches columns to the right of its own,
 * and only restyles a tab when it creates that tab (or when asked to refresh).
 */
var TOKEN = '__TOKEN__';
var VERSION = 6;
var BOOK_TITLE = 'New IT Companies';

var INK = '#1d1f1e', MUTE = '#6b6f6a', FAINT = '#9b9f99', LINE = '#e3e4df', HAIR = '#eeeeea';
var PANEL = '#f8f8f5', HEAD_BG = '#f4f4f0', ACCENT = '#14614f', FONT = 'Inter';

// key, header, width. The first VISIBLE columns stay in view; the rest sit in a collapsed group.
var COLS = [
  ['company', 'Company', 270], ['website', 'Website', 210], ['email', 'Email', 260],
  ['phone', 'Phone', 140], ['address', 'Address', 390], ['registered', 'Registered', 112],
  ['contact', 'Contact', 220], ['contact_email', 'Contact email', 240], ['linkedin', 'LinkedIn', 100],
  ['industry', 'Industry', 220], ['state', 'State', 60], ['source', 'Source', 120], ['fit', 'Fit', 190],
  ['proof', 'Verified by', 420], ['added', 'Added', 112], ['id', 'ID', 120]
];
var VISIBLE = 6;
var ROW_H = 32;
var TEXT_KEYS = ['company', 'phone', 'address', 'contact', 'contact_email', 'industry', 'state', 'source', 'fit', 'proof', 'id'];

// ------------------------------------------------------------------ web app
function doGet() {
  return json_({ ok: true, service: 'it-leads', version: VERSION });
}

function doPost(e) {
  var out;
  try {
    var req = JSON.parse(e.postData.contents);
    if (req.token !== TOKEN) throw new Error('Wrong token. Run setup again to get a matching script.');
    var lock = LockService.getScriptLock();
    lock.waitLock(60000);
    try { out = route_(req); } finally { lock.releaseLock(); }
  } catch (err) {
    out = { ok: false, error: String(err && err.message ? err.message : err) };
  }
  return json_(out);
}

function json_(o) {
  return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);
}

function route_(req) {
  var out;
  if (req.action === 'ping') out = ping_();
  else if (req.action === 'init') out = init_(req);
  else if (req.action === 'share') out = share_(req);
  else if (req.action === 'upsert') out = upsert_(req);
  else if (req.action === 'log') out = log_(req);
  else if (req.action === 'dashboard') out = dashboard_(req);
  else throw new Error('Unknown action: ' + req.action);
  out.version = VERSION;
  return out;
}

// --------------------------------------------------------------------- book
function props_() { return PropertiesService.getScriptProperties(); }

function book_(create) {
  var id = props_().getProperty('SHEET_ID');
  if (id) {
    try { return SpreadsheetApp.openById(id); }
    catch (err) { throw new Error('Could not open the sheet this script created. Is it in the trash? ' + err); }
  }
  if (!create) return null;
  var ss = SpreadsheetApp.create(BOOK_TITLE);
  props_().setProperty('SHEET_ID', ss.getId());
  return ss;
}

function colOf_(key) {
  for (var i = 0; i < COLS.length; i++) if (COLS[i][0] === key) return i + 1;
  throw new Error('No column ' + key);
}

function letter_(n) {
  var s = '';
  while (n > 0) { var m = (n - 1) % 26; s = String.fromCharCode(65 + m) + s; n = Math.floor((n - 1) / 26); }
  return s;
}

function linked_(ss) {
  try {
    var access = DriveApp.getFileById(ss.getId()).getSharingAccess();
    return access === DriveApp.Access.ANYONE_WITH_LINK || access === DriveApp.Access.ANYONE;
  } catch (err) { return false; }
}

// A work or school account can forbid sharing by link. That must not break the connection: report it instead.
function setLink_(ss, on) {
  try {
    var file = DriveApp.getFileById(ss.getId());
    if (on) file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    else file.setSharing(DriveApp.Access.PRIVATE, DriveApp.Permission.NONE);
    return '';
  } catch (err) { return String(err && err.message ? err.message : err); }
}

function share_(req) {
  var ss = book_(false);
  if (!ss) throw new Error('There is no sheet yet.');
  var problem = setLink_(ss, !!req.link);
  return { ok: true, shared: linked_(ss), share_error: problem };
}

function ping_() {
  var ss = book_(false);
  return { ok: true, configured: !!ss, url: ss ? ss.getUrl() : '', id: ss ? ss.getId() : '', shared: ss ? linked_(ss) : false };
}

function init_(req) {
  var ss = book_(true);
  if (req.tz && ss.getSpreadsheetTimeZone() !== req.tz) ss.setSpreadsheetTimeZone(req.tz);
  var refresh = !!req.refresh;
  var dash = ss.getSheetByName('Dashboard');
  var co = ss.getSheetByName('Companies');
  var runs = ss.getSheetByName('_runs');
  var made = { dash: false, co: false, runs: false };
  if (!dash) {
    var first = ss.getSheetByName('Sheet1');
    if (first && !co && !runs) { first.setName('Dashboard'); dash = first; }
    else dash = ss.insertSheet('Dashboard', 0);
    made.dash = true;
  }
  if (!co) { co = ss.insertSheet('Companies', 1); made.co = true; }
  if (!runs) { runs = ss.insertSheet('_runs', 2); made.runs = true; }
  if (made.co || refresh) formatCompanies_(co);
  if (made.runs || refresh) formatRuns_(runs);
  if (made.dash || refresh) formatDashboard_(dash);
  if (made.dash) ss.setActiveSheet(dash);
  var have = {};
  ss.getEditors().forEach(function (u) { have[String(u.getEmail()).toLowerCase()] = true; });
  var emails = req.share || [];
  for (var i = 0; i < emails.length; i++) {
    var em = String(emails[i] || '').trim().toLowerCase();
    if (em && !have[em]) ss.addEditor(em);
  }
  if (made.runs) runs.hideSheet();
  var problem = '';
  if (req.link !== undefined && req.link !== null) problem = setLink_(ss, !!req.link);
  return {
    ok: true, id: ss.getId(), url: ss.getUrl(), shared: linked_(ss), share_error: problem,
    gid_dashboard: dash.getSheetId(), gid_companies: co.getSheetId()
  };
}

// ---------------------------------------------------------------- Companies
function formatCompanies_(sh) {
  var n = COLS.length;
  if (sh.getMaxColumns() < n) sh.insertColumnsAfter(sh.getMaxColumns(), n - sh.getMaxColumns());
  var rows = sh.getMaxRows();
  var all = sh.getRange(1, 1, rows, n);
  all.setFontFamily(FONT).setFontSize(10).setFontColor(INK).setBackground('#ffffff')
    .setVerticalAlignment('middle').setHorizontalAlignment('left')
    .setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP);
  var head = sh.getRange(1, 1, 1, n);
  head.setValues([COLS.map(function (c) { return c[1].toUpperCase(); })])
    .setFontSize(8).setFontWeight('bold').setFontColor(MUTE).setBackground(HEAD_BG)
    .setBorder(false, false, true, false, false, false, LINE, SpreadsheetApp.BorderStyle.SOLID_MEDIUM);
  sh.setRowHeight(1, 36);
  if (rows > 1) sh.setRowHeights(2, rows - 1, ROW_H);
  for (var i = 0; i < n; i++) sh.setColumnWidth(i + 1, COLS[i][2]);
  sh.setFrozenRows(1);
  sh.setFrozenColumns(1);
  sh.setHiddenGridlines(true);
  sh.getRange(2, colOf_('registered'), Math.max(rows - 1, 1), 1).setNumberFormat('d mmm yyyy');
  sh.getRange(2, colOf_('added'), Math.max(rows - 1, 1), 1).setNumberFormat('d mmm yyyy');
  var grouped = false;
  try { grouped = !!sh.getColumnGroup(VISIBLE + 1, 1); } catch (err) { grouped = false; }
  if (!grouped) {
    sh.getRange(1, VISIBLE + 1, 1, n - VISIBLE).shiftColumnGroupDepth(1);
    sh.getColumnGroup(VISIBLE + 1, 1).collapse();
  }
  if (!sh.getFilter()) sh.getRange(1, 1, rows, n).createFilter();
}

function formatRuns_(sh) {
  var heads = ['When', 'Seconds', 'New', 'Held back', 'Updated', 'Sources', 'Status', 'Errors'];
  if (sh.getMaxColumns() < heads.length) sh.insertColumnsAfter(sh.getMaxColumns(), heads.length - sh.getMaxColumns());
  sh.getRange(1, 1, 1, heads.length).setValues([heads]).setFontFamily(FONT).setFontWeight('bold');
}

function dateCell_(iso, tz) {
  if (!iso || !/^\d{4}-\d{2}-\d{2}$/.test(String(iso))) return '';
  try { return Utilities.parseDate(String(iso), tz, 'yyyy-MM-dd'); } catch (err) { return ''; }
}

function link_(text, url) {
  var style = SpreadsheetApp.newTextStyle().setForegroundColor(ACCENT).setUnderline(false).build();
  return SpreadsheetApp.newRichTextValue().setText(text).setLinkUrl(url).setTextStyle(style).build();
}

function plain_(text) {
  return SpreadsheetApp.newRichTextValue().setText(text || '').build();
}

function site_(url) {
  return String(url || '').replace(/^https?:\/\/(www\.)?/, '').replace(/\/+$/, '');
}

function linkCells_(r) {
  return [
    r.website ? link_(site_(r.website), r.website) : plain_(''),
    r.email ? link_(r.email, 'mailto:' + r.email) : plain_(''),
    r.linkedin ? link_(r.linkedin_label || 'Profile', r.linkedin) : plain_('')
  ];
}

function rowValues_(r, tz, today) {
  return COLS.map(function (c) {
    var k = c[0];
    if (k === 'website' || k === 'email' || k === 'linkedin') return '';
    if (k === 'registered') return dateCell_(r.registered, tz);
    if (k === 'added') return dateCell_(today, tz);
    return r[k] === undefined || r[k] === null ? '' : String(r[k]);
  });
}

function upsert_(req) {
  var ss = book_(false);
  if (!ss) throw new Error('There is no sheet yet. Run setup first.');
  var sh = ss.getSheetByName('Companies');
  if (!sh) throw new Error('The Companies tab is missing. Run setup again.');
  var tz = ss.getSpreadsheetTimeZone();
  var n = COLS.length;
  var idCol = colOf_('id');
  var last = sh.getLastRow();
  var existing = {};
  if (last > 1) {
    var ids = sh.getRange(2, idCol, last - 1, 1).getValues();
    for (var i = 0; i < ids.length; i++) if (ids[i][0]) existing[String(ids[i][0])] = i + 2;
  }
  var inserts = [], updates = [], skipped = 0, seen = {};
  (req.rows || []).forEach(function (r) {
    if (!r || !r.id || !r.company || seen[r.id]) { skipped++; return; }
    seen[r.id] = true;
    if (existing[r.id]) updates.push({ row: existing[r.id], r: r }); else inserts.push(r);
  });

  // Existing rows first (inserting above moves them): only empty cells are filled, nothing a person typed is replaced.
  updates.forEach(function (u) {
    try {
      var r = u.r;
      var cur = sh.getRange(u.row, 1, 1, n).getValues()[0];
      ['company', 'phone', 'address', 'contact', 'contact_email', 'industry', 'state', 'source', 'fit', 'proof'].forEach(function (k) {
        if (r[k] && !cur[colOf_(k) - 1]) sh.getRange(u.row, colOf_(k)).setValue(String(r[k]));
      });
      if (r.registered && !cur[colOf_('registered') - 1]) sh.getRange(u.row, colOf_('registered')).setValue(dateCell_(r.registered, tz));
      var cells = linkCells_(r);
      if (r.website && !cur[colOf_('website') - 1]) sh.getRange(u.row, colOf_('website')).setRichTextValue(cells[0]);
      if (r.email && !cur[colOf_('email') - 1]) sh.getRange(u.row, colOf_('email')).setRichTextValue(cells[1]);
      if (r.linkedin && !cur[colOf_('linkedin') - 1]) sh.getRange(u.row, colOf_('linkedin')).setRichTextValue(cells[2]);
    } catch (err) { skipped++; }
  });

  // New rows go in just under the header, newest filing first, so rows below (and any columns you add to the
  // right) stay exactly where they are.
  if (inserts.length) {
    inserts.sort(function (a, b) { return String(b.registered || '').localeCompare(String(a.registered || '')); });
    var m = inserts.length;
    sh.insertRowsBefore(2, m);
    var range = sh.getRange(2, 1, m, n);
    range.setFontFamily(FONT).setFontSize(10).setFontWeight('normal').setFontColor(INK).setBackground('#ffffff')
      .setVerticalAlignment('middle').setHorizontalAlignment('left')
      .setWrapStrategy(SpreadsheetApp.WrapStrategy.CLIP)
      .setBorder(false, false, true, false, false, false, HAIR, SpreadsheetApp.BorderStyle.SOLID);
    sh.setRowHeights(2, m, ROW_H);
    TEXT_KEYS.forEach(function (k) { sh.getRange(2, colOf_(k), m, 1).setNumberFormat('@'); });   // text stays text
    range.setValues(inserts.map(function (r) { return rowValues_(r, tz, req.today); }));
    sh.getRange(2, colOf_('registered'), m, 1).setNumberFormat('d mmm yyyy');
    sh.getRange(2, colOf_('added'), m, 1).setNumberFormat('d mmm yyyy');
    var cells = inserts.map(linkCells_);
    sh.getRange(2, colOf_('website'), m, 1).setRichTextValues(cells.map(function (c) { return [c[0]]; }));
    sh.getRange(2, colOf_('email'), m, 1).setRichTextValues(cells.map(function (c) { return [c[1]]; }));
    sh.getRange(2, colOf_('linkedin'), m, 1).setRichTextValues(cells.map(function (c) { return [c[2]]; }));
  }
  return { ok: true, inserted: inserts.length, updated: updates.length, skipped: skipped,
           total: Math.max(sh.getLastRow() - 1, 0) };
}

// ---------------------------------------------------------------- Dashboard
function formatDashboard_(sh) {
  sh.getRange(1, 1, sh.getMaxRows(), sh.getMaxColumns()).breakApart();
  sh.clear();
  sh.setHiddenGridlines(true);
  sh.setColumnWidth(1, 28);
  for (var c = 2; c <= 13; c++) sh.setColumnWidth(c, 100);
  sh.getRange(1, 1, sh.getMaxRows(), sh.getMaxColumns())
    .setFontFamily(FONT).setFontSize(10).setFontColor(INK).setBackground('#ffffff')
    .setVerticalAlignment('middle').setHorizontalAlignment('left');
  sh.setRowHeight(1, 24);
  sh.getRange('B2:H2').merge().setValue('New IT company filings').setFontSize(20).setFontWeight('bold');
  sh.setRowHeight(2, 42);
  sh.getRange('B3:M3').merge().setFontSize(10).setFontColor(MUTE);
  sh.setRowHeight(3, 22);
  sh.setRowHeight(4, 18);

  // Whole-column references on purpose: new rows are inserted at the top of Companies, and a range such as $O$2:$O
  // would be pushed down by every insert until it pointed at empty rows (the tiles then read 0).
  var A = 'Companies!$' + letter_(colOf_('added')) + ':$' + letter_(colOf_('added'));
  var NAME = 'Companies!$A:$A';
  var EMAIL = 'Companies!$' + letter_(colOf_('email')) + ':$' + letter_(colOf_('email'));
  var PHONE = 'Companies!$' + letter_(colOf_('phone')) + ':$' + letter_(colOf_('phone'));
  var tiles = [
    [2, 'LATEST ADDITIONS', '=COUNTIF(' + A + ',MAX(' + A + '))',
      '=IF(MAX(' + A + ')=0,"nothing yet","added on "&TEXT(MAX(' + A + '),"d mmm yyyy"))'],
    [5, 'LAST 7 DAYS', '=COUNTIFS(' + A + ',">="&(TODAY()-6))', 'including today'],
    [8, 'TOTAL LISTED', '=MAX(0,COUNTA(' + NAME + ')-1)', 'in this sheet'],
    [11, 'EMAIL AND PHONE', '=MAX(0,COUNTIFS(' + EMAIL + ',"<>",' + PHONE + ',"<>")-1)', 'can be reached both ways']
  ];
  tiles.forEach(function (t) {
    var col = t[0];
    sh.getRange(5, col, 1, 3).merge().setValue(t[1]).setFontSize(8).setFontWeight('bold').setFontColor(MUTE)
      .setHorizontalAlignment('center');
    var v = sh.getRange(6, col, 1, 3).merge();
    if (typeof t[2] === 'string') v.setFormula(t[2]); else v.setValue(t[2]);
    v.setFontSize(28).setFontWeight('bold').setFontColor(INK).setHorizontalAlignment('center');
    var cap = sh.getRange(7, col, 1, 3).merge().setFontSize(9).setFontColor(FAINT).setHorizontalAlignment('center');
    if (t[3].charAt(0) === '=') cap.setFormula(t[3]); else cap.setValue(t[3]);
    sh.getRange(5, col, 3, 3).setBackground(PANEL)
      .setBorder(true, true, true, true, false, false, LINE, SpreadsheetApp.BorderStyle.SOLID);
  });
  sh.setRowHeight(5, 28);
  sh.setRowHeight(6, 52);
  sh.setRowHeight(7, 26);
  sh.setRowHeight(8, 22);

  sh.getRange('B9').setValue('LAST 12 DAYS').setFontSize(8).setFontWeight('bold').setFontColor(MUTE);
  sh.getRange('B10:M10').merge()
    .setFormula('=SPARKLINE(B12:M12,{"charttype","column";"color","' + ACCENT + '";"empty","zero"})');
  sh.setRowHeight(10, 64);
  for (var d = 0; d < 12; d++) {
    sh.getRange(11, 2 + d).setFormula('=TODAY()-' + (11 - d)).setNumberFormat('d mmm');
    sh.getRange(12, 2 + d).setFormula('=COUNTIF(' + A + ',' + letter_(2 + d) + '11)');
  }
  sh.getRange('B11:M11').setFontSize(8).setFontColor(FAINT).setHorizontalAlignment('center');
  sh.getRange('B12:M12').setFontSize(10).setHorizontalAlignment('center');
  sh.setRowHeight(11, 20);
  sh.setRowHeight(12, 24);
  sh.setRowHeight(13, 24);

  sh.getRange('B14').setValue('BY STATE').setFontSize(8).setFontWeight('bold').setFontColor(MUTE);
  sh.getRange('G14').setValue('BY REGISTRY').setFontSize(8).setFontWeight('bold').setFontColor(MUTE);
  sh.getRange('B24').setValue('RECENT RUNS').setFontSize(8).setFontWeight('bold').setFontColor(MUTE);
  sh.setRowHeight(14, 24);
  sh.setRowHeight(24, 24);
}

function tally_(sh, key, limit) {
  var last = sh.getLastRow();
  var counts = {};
  if (last > 1) {
    var vals = sh.getRange(2, colOf_(key), last - 1, 1).getValues();
    for (var i = 0; i < vals.length; i++) {
      var v = String(vals[i][0] || '').trim();
      if (v) counts[v] = (counts[v] || 0) + 1;
    }
  }
  return Object.keys(counts).map(function (k) { return [k, counts[k]]; })
    .sort(function (a, b) { return b[1] - a[1]; }).slice(0, limit);
}

function writeTable_(dash, row, col, rows, limit) {
  dash.getRange(row, col, limit, 2).clearContent();
  if (!rows.length) return;
  var r = dash.getRange(row, col, rows.length, 2);
  r.setValues(rows);
  r.setFontSize(10).setFontColor(INK);
  dash.getRange(row, col + 1, rows.length, 1).setHorizontalAlignment('right');
  r.setBorder(false, false, true, false, false, true, HAIR, SpreadsheetApp.BorderStyle.SOLID);
}

function safe_(v) {
  var t = String(v === undefined || v === null ? '' : v);
  return /^[=+\-@]/.test(t) ? "'" + t : t;
}

function log_(req) {
  var ss = book_(false);
  if (!ss) throw new Error('There is no sheet yet. Run setup first.');
  var run = req.run || {};
  var runs = ss.getSheetByName('_runs');
  runs.appendRow([
    safe_(run.started), Number(run.seconds) || 0, Number(run.added) || 0, Number(run.held) || 0, Number(run.updated) || 0,
    safe_(run.sources), safe_(run.status || 'ok'), safe_(run.errors)
  ]);
  paintDashboard_(ss, req);
  return { ok: true };
}

// Rewrites the Dashboard tab from what is in Companies and _runs. Without a new run in the log: used to repair the tab.
function dashboard_(req) {
  var ss = book_(false);
  if (!ss) throw new Error('There is no sheet yet. Run setup first.');
  var dash = ss.getSheetByName('Dashboard');
  if (dash) formatDashboard_(dash);
  paintDashboard_(ss, req);
  return { ok: true };
}

function paintDashboard_(ss, req) {
  var tz = ss.getSpreadsheetTimeZone();
  var dash = ss.getSheetByName('Dashboard');
  var co = ss.getSheetByName('Companies');
  var runs = ss.getSheetByName('_runs');
  // A tab written by an older script has formulas whose ranges drifted down: rebuild it once.
  if (String(dash.getRange('H6').getFormula() || '').indexOf('Companies!$A:$A') < 0) formatDashboard_(dash);
  var when = Utilities.formatDate(new Date(), tz, 'd MMM yyyy, HH:mm');
  dash.getRange('B3').setValue('Updated ' + when + '   |   ' + (req.sources_active || 0) +
    ' registries   |   next run ' + safe_(req.next_run || ''));
  writeTable_(dash, 15, 2, tally_(co, 'state', 8), 8);
  writeTable_(dash, 15, 7, tally_(co, 'source', 8), 8);
  var lastRun = runs.getLastRow();
  var take = Math.min(6, Math.max(lastRun - 1, 0));
  dash.getRange(25, 2, 6, 11).clearContent();
  if (take > 0) {
    var data = runs.getRange(lastRun - take + 1, 1, take, 8).getValues().reverse();
    var rows = data.map(function (d) {
      return [d[0], '', d[2] + ' added', '', '', d[5], '', '', '', '', d[6]];
    });
    var out = dash.getRange(25, 2, rows.length, 11);
    out.setValues(rows);
    out.setFontSize(9).setFontColor(INK)
      .setBorder(false, false, true, false, false, true, HAIR, SpreadsheetApp.BorderStyle.SOLID);
  }
}
